import { CheckCircle, EnvelopeOpen, FileText, ShieldCheck, UserCircle } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { DeepViewShell, DetailCard, FactList, StatusPill } from "../../components/DeepViewShell";
import { FarmSelect } from "../../components/FarmSelect";
import { StatePanel } from "../../components/StatePanel";
import type { CompanyJobData, JobApplicationInput } from "../../types";
import { useCompanyData } from "./useCompanyData";

const emptyInput: JobApplicationInput = { introduction: "", availability: "", preferredWork: "Harvest and packing", rulesAccepted: false };

export function JobApplicationView() {
  const request = useMemo(() => ({ kind: "companyJobApplication" } as const), []);
  const { model, data, notice, pending, act } = useCompanyData<CompanyJobData>(request);
  const navigate = useNavigate();
  const [localInput, setLocalInput] = useState<JobApplicationInput>();
  const [confirm, setConfirm] = useState<"submit" | "withdraw" | "accept_invite">();
  if (!model || model.state === "loading") return <StatePanel state="loading" />;
  if (model.state !== "ready" || !data) return <StatePanel state={model.state === "ready" ? "empty" : model.state} />;
  const application = data.application;
  const input = localInput ?? (application ? { introduction: application.introduction, availability: application.availability, preferredWork: application.preferredWork, rulesAccepted: application.rulesAccepted } : emptyInput);
  const editable = !application || ["draft", "rejected", "withdrawn"].includes(application.status);
  const submit = async () => { if (confirm === "submit") await act({ type: "jobApplication.submit", input }); if (confirm === "withdraw" && application) await act({ type: "jobApplication.withdraw", applicationId: application.id }); if (confirm === "accept_invite" && data.invitation) await act({ type: "staffInvitation.accept", invitationId: data.invitation.id }); setConfirm(undefined); };
  const save = () => void act({ type: "jobApplication.saveDraft", input });
  return <DeepViewShell eyebrow="Public employment path" title="Job Application" subtitle="One persistent application per character · farming information only" breadcrumb={["Company", "Job Application"]} backLabel="Back to Company Profile" onBack={() => navigate("/company/profile")} status={<StatusPill tone={application?.status === "accepted" ? "success" : application?.status === "rejected" ? "danger" : "warning"}>{application?.status.replace("_", " ") ?? "Not Started"}</StatusPill>} actionBar={<><div className="domain-action-summary"><span>{data.invitation ? `Invitation · ${data.invitation.role}` : application ? application.id.toUpperCase() : "New application"}</span><p>{application?.updatedAt ?? "Nothing has been saved"}</p></div><div className="domain-action-group">{data.invitation ? <button type="button" className="domain-primary-action" onClick={() => setConfirm("accept_invite")}>Accept Staff Invitation</button> : editable ? <><button type="button" className="domain-secondary-action" disabled={pending} onClick={save}>Save Draft</button><button type="button" className="domain-primary-action" disabled={pending || !input.rulesAccepted} onClick={() => setConfirm("submit")}>Submit Application</button></> : application && ["submitted", "under_review", "interview"].includes(application.status) ? <button type="button" className="domain-secondary-action danger" onClick={() => setConfirm("withdraw")}>Withdraw Application</button> : null}</div></>}>
    {notice ? <div className="domain-notice domain-notice--inline">{notice}</div> : null}
    {data.invitation ? <DetailCard eyebrow="Staff invitation" title={`Join as ${data.invitation.role}`}><p className="domain-emphasis"><EnvelopeOpen size={24} />Invited by {data.invitation.invitedBy}</p><FactList facts={[{ label: "Company", value: "Grapeseed Farm Co." }, { label: "Role", value: data.invitation.role }, { label: "Expires", value: data.invitation.expiresAt }, { label: "Status", value: data.invitation.status }]} /></DetailCard> : null}
    <div className="domain-two-column"><div className="domain-card-stack"><DetailCard eyebrow="Character statement" title="Why do you want to work here?"><label className="company-text-field"><span>Short introduction</span><textarea disabled={!editable} maxLength={220} value={input.introduction} onChange={(event) => setLocalInput({ ...input, introduction: event.target.value })} /><small>{input.introduction.length} / 220</small></label><label className="company-text-field"><span>Availability note</span><input disabled={!editable} value={input.availability} onChange={(event) => setLocalInput({ ...input, availability: event.target.value })} /></label><FarmSelect label="Preferred Work" disabled={!editable} value={input.preferredWork} options={["Planting and care", "Harvest and packing", "Field logistics", "General farm work"].map((item) => ({ value: item, label: item, description: "Preference only · no guaranteed Assignment" }))} onChange={(value) => setLocalInput({ ...input, preferredWork: value })} /></DetailCard></div><div className="domain-card-stack"><DetailCard eyebrow="Company rules" title="Before submission"><ul className="domain-check-list"><li><CheckCircle size={18} />Pay follows validated Assignments</li><li><CheckCircle size={18} />Company Cargo must reach Warehouse</li><li><CheckCircle size={18} />Issued assets remain Company-owned</li></ul><label className="company-check-field"><input type="checkbox" disabled={!editable} checked={input.rulesAccepted} onChange={(event) => setLocalInput({ ...input, rulesAccepted: event.target.checked })} /><span><ShieldCheck size={19} />I acknowledge the Company rules</span></label></DetailCard><DetailCard eyebrow="Privacy" title="No invented credentials"><p className="domain-emphasis"><UserCircle size={23} />Only identity, this statement, availability and permitted farming history are reviewed.</p></DetailCard></div></div>
    {confirm ? <ConfirmDialog eyebrow="Employment confirmation" title={confirm === "submit" ? "Submit this Job Application?" : confirm === "withdraw" ? "Withdraw your active application?" : "Accept this Staff invitation?"} confirmLabel={confirm === "submit" ? "Submit Application" : confirm === "withdraw" ? "Withdraw Application" : "Accept Invitation"} tone={confirm === "withdraw" ? "danger-confirm" : "confirm"} pending={pending} onClose={() => setConfirm(undefined)} onConfirm={() => void submit()}><p><FileText size={18} /> The company will revalidate that no other active employment record exists.</p></ConfirmDialog> : null}
  </DeepViewShell>;
}
