import { ArrowSquareOut, CalendarCheck, Coins, MapPin, Plant, ShieldWarning, Warning } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { DeepViewShell, DetailCard, FactList, StatusPill } from "../../components/DeepViewShell";
import { StatePanel } from "../../components/StatePanel";
import type { CompanyLease } from "../../types";
import { useCompanyData } from "./useCompanyData";

type LeaseAction = "start" | "pay" | "end";

export function LeaseDetailView() {
  const { leaseId = "" } = useParams();
  const request = useMemo(() => ({ kind: "companyLeaseDetail", leaseId } as const), [leaseId]);
  const { model, data, notice, pending, act } = useCompanyData<CompanyLease>(request);
  const navigate = useNavigate();
  const [action, setAction] = useState<LeaseAction>();
  if (!model || model.state === "loading") return <StatePanel state="loading" />;
  if (model.state !== "ready" || !data) return <StatePanel state={model.state === "ready" ? "empty" : model.state} title="Lease unavailable" body="This Lease identifier is missing or outside your authority." actionLabel="Back to Leases" onAction={() => navigate("/company/leases")} />;
  const submit = async () => { const result = await act({ type: "lease.transition", leaseId: data.id, action: action! }); setAction(undefined); if (result.ok && action === "end") navigate("/company/leases"); };
  const openField = () => navigate(`/fields/${data.fieldId}`);
  const urgent = data.status === "grace" || data.status === "expired";
  return <DeepViewShell eyebrow="Land access record" title={data.fieldName} subtitle={`${data.location} · ${data.billing}`} breadcrumb={["Company", "Leases", data.fieldName]} backLabel="Back to Leases" onBack={() => navigate("/company/leases")} status={<StatusPill tone={urgent ? "danger" : data.status === "active" || data.status === "starter" ? "success" : "neutral"}>{data.status.replace("_", " ")}</StatusPill>} actionBar={<><div className="domain-action-summary"><span>{data.graceDeadline ? `Grace ends ${data.graceDeadline}` : data.nextPayment ? `Next payment ${data.nextPayment}` : data.billing}</span><p>{data.restriction ?? `${data.capacity} planting slots authorized`}</p></div><div className="domain-action-group">{data.availableActions.includes("open_field") ? <button type="button" className="domain-secondary-action" onClick={openField}>Open Field<ArrowSquareOut size={17} /></button> : null}{data.availableActions.includes("end") ? <button type="button" className="domain-secondary-action danger" onClick={() => setAction("end")}>End Lease</button> : null}{data.availableActions.includes("pay") ? <button type="button" className="domain-primary-action" onClick={() => setAction("pay")}><Coins size={18} />{data.status === "grace" ? "Resolve Grace Period" : "Pay Lease"}</button> : null}{data.availableActions.includes("start") ? <button type="button" className="domain-primary-action" onClick={() => setAction("start")}><Plant size={18} />Start Lease</button> : null}</div></>}>
    {notice ? <div className="domain-notice domain-notice--inline">{notice}</div> : null}
    {data.status === "grace" ? <div className="lease-grace-banner"><Warning size={25} /><span><strong>24-hour Grace Period is active</strong><small>New planting is suspended. Existing care and harvest remain permitted until {data.graceDeadline}.</small></span></div> : null}
    <div className="domain-two-column lease-detail-layout"><div className="domain-card-stack"><DetailCard eyebrow="Lease terms" title="Access and billing"><FactList facts={[{ label: "Field", value: data.fieldName }, { label: "Location", value: data.location }, { label: "Status", value: data.status.replace("_", " ") }, { label: "Recurring cost", value: data.recurringPrice ? `$${data.recurringPrice.toLocaleString("en-US")}` : "Included starter Field" }, { label: "Billing", value: data.billing }, { label: "Next payment", value: data.nextPayment ?? "Not applicable" }, { label: "Capacity", value: `${data.capacity} slots` }]} /></DetailCard><DetailCard eyebrow="Agronomic scope" title="Permitted crops"><div className="lease-crop-list">{data.allowedCrops.map((crop) => <span key={crop}><Plant size={16} />{crop}</span>)}</div><p className="domain-muted">Current production · {data.activeCrops}</p></DetailCard></div><div className="domain-card-stack"><DetailCard eyebrow="Operational dependency" title={`${data.linkedWork.length} linked Work records`}>{data.linkedWork.length ? <ul className="domain-check-list">{data.linkedWork.map((work) => <li key={work}><CalendarCheck size={18} />{work}</li>)}</ul> : <p className="domain-muted">No active Assignment, Contract or Buyer Order is linked.</p>}</DetailCard><DetailCard eyebrow="Restriction contract" title={data.restriction ? "Restriction active" : "Access current"}><p className={`domain-emphasis ${data.restriction ? "warning" : ""}`}>{data.restriction ? <ShieldWarning size={23} /> : <MapPin size={23} />}{data.restriction ?? "Planning, field work and authorized access remain available."}</p></DetailCard></div></div>
    {action ? <ConfirmDialog eyebrow="Lease authority" title={action === "start" ? `Lease ${data.fieldName}?` : action === "pay" ? data.status === "grace" ? "Resolve this Grace Period?" : "Pay this Lease now?" : "End this Lease?"} confirmLabel={action === "start" ? "Start Lease" : action === "pay" ? "Confirm Payment" : "End Lease"} tone={action === "end" ? "danger-confirm" : "confirm"} pending={pending} onClose={() => setAction(undefined)} onConfirm={() => void submit()}><FactList facts={[{ label: "Treasury movement", value: action === "end" ? "$0" : `$${data.recurringPrice.toLocaleString("en-US")}` }, { label: "Field effect", value: action === "end" ? "Access becomes unavailable" : "Planting access becomes active" }, { label: "Linked Work", value: `${data.linkedWork.length} records revalidated` }, { label: "Ledger", value: action === "end" ? "Access event" : "Immutable payment entry" }]} /><p>The adapter revalidates Treasury, Lease status and Field access as one fixture mutation.</p></ConfirmDialog> : null}
  </DeepViewShell>;
}
