import { ArrowRight, CheckCircle, Clock, LockKey, ShieldCheck, Warning } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { DeepViewShell, DetailCard, FactList, StatusPill } from "../../components/DeepViewShell";
import { StatePanel } from "../../components/StatePanel";
import type { BusinessSaleListing } from "../../types";
import { useCompanyData } from "./useCompanyData";

const money = (value: number) => `$${value.toLocaleString()}`;

export function SaleReviewView() {
  const request = useMemo(() => ({ kind: "companySaleReview" } as const), []);
  const { model, data, notice, pending, act, context } = useCompanyData<BusinessSaleListing>(request);
  const navigate = useNavigate();
  const [confirm, setConfirm] = useState<"publish" | "cancel">();
  if (!model || model.state === "loading") return <StatePanel state="loading" />;
  if (model.state !== "ready" || !data) return <StatePanel state={model.state === "ready" ? "empty" : model.state} />;
  const submit = async () => { const result = confirm === "publish" ? await act({ type: "businessSale.publish", listingId: data.id }) : await act({ type: "businessSale.cancel", listingId: data.id }); setConfirm(undefined); if (result.ok && confirm === "cancel") navigate("/company/sale"); };
  return <DeepViewShell eyebrow="Immutable listing review" title="Sale Listing Review" subtitle={`${data.id.toUpperCase()} · version ${data.version} · material changes require a new public version`} breadcrumb={["Company", "Business Sale", "Review"]} backLabel="Back to Business Sale" onBack={() => navigate("/company/sale")} status={<StatusPill tone={data.status === "listing_changed" ? "danger" : data.status === "draft" ? "neutral" : "warning"}>{data.status.replace("_", " ")}</StatusPill>} actionBar={<><div className="domain-action-summary"><span>{money(data.askingPrice)} public asking price</span><p>{data.expiresAt ? `Expires ${data.expiresAt}` : "Not yet public"}</p></div><div className="domain-action-group">{data.availableActions.includes("cancel") ? <button type="button" className="domain-secondary-action danger" onClick={() => setConfirm("cancel")}>Cancel Listing</button> : null}{data.availableActions.includes("publish") ? <button type="button" className="domain-primary-action" onClick={() => setConfirm("publish")}><ShieldCheck size={18} />Publish Listing</button> : null}{data.status === "awaiting_seller" ? <button type="button" className="domain-primary-action" onClick={() => navigate(`/company/sale/transfer/${data.id}`)}>Review Transfer<ArrowRight size={16} /></button> : null}</div></>}>
    {notice ? <div className="domain-notice domain-notice--inline">{notice}</div> : null}
    {data.status === "listing_changed" ? <div className="sale-change-banner"><Warning size={23} /><span><strong>Public listing requires revalidation</strong><small>Buyer escrow, if any, has been returned. Cancel this version before editing.</small></span></div> : null}
    <div className="domain-two-column sale-review-layout"><div className="domain-card-stack"><DetailCard eyebrow="Immutable snapshot" title={data.companyName}><FactList facts={[{ label: "Listing", value: data.id.toUpperCase() }, { label: "Version", value: data.version }, { label: "Asking price", value: money(data.askingPrice) }, { label: "Treasury included", value: money(data.treasuryIncluded) }, { label: "Warehouse valuation", value: money(data.warehouseValuation) }, { label: "Active Leases", value: data.activeLeases }, { label: "Staff retained", value: data.staffCount }]} /></DetailCard><DetailCard eyebrow="Obligations" title="Buyer assumes operations"><FactList facts={[{ label: "Active obligations", value: money(data.activeObligations) }, { label: "Registry fee", value: money(data.saleFee) }, { label: "Seller proceeds", value: money(data.sellerProceeds) }, { label: "Escrow held", value: money(data.escrowAmount) }]} /></DetailCard></div><div className="domain-card-stack"><DetailCard eyebrow="Publication checks" title="Ready for public listing"><ul className="domain-check-list"><li><CheckCircle size={18} />Company assets and obligations snapshot captured</li><li><CheckCircle size={18} />Staff continuity disclosed</li><li><CheckCircle size={18} />Buyer funds must enter escrow before reservation</li><li><CheckCircle size={18} />Seller and buyer identity revalidated at Registry</li></ul></DetailCard><DetailCard eyebrow="Physical authority" title="Office publication"><FactList facts={[{ label: "Surface", value: context.surface }, { label: "Presence", value: context.presence }, { label: "Required", value: "Office Terminal · Office presence" }]} /><p className="domain-emphasis"><LockKey size={22} />Publishing does not transfer ownership or move buyer funds.</p></DetailCard></div></div>
    {confirm ? <ConfirmDialog eyebrow="Business Sale" title={confirm === "publish" ? "Publish this immutable listing?" : "Cancel this listing version?"} confirmLabel={confirm === "publish" ? "Publish Listing" : "Cancel Listing"} tone={confirm === "cancel" ? "danger-confirm" : "confirm"} pending={pending} onClose={() => setConfirm(undefined)} onConfirm={() => void submit()}><FactList facts={[{ label: "Listing version", value: data.version }, { label: "Asking price", value: money(data.askingPrice) }, { label: "Action location", value: confirm === "publish" ? "Office Terminal" : "Owner authority" }, { label: "Public effect", value: confirm === "publish" ? "Visitor purchase opens" : "Listing removed" }]} /><p><Clock size={17} /> The adapter will reject this confirmation if the snapshot changed while the dialog was open.</p></ConfirmDialog> : null}
  </DeepViewShell>;
}
