import { IdentificationBadge, Package, ShieldWarning, Toolbox, Warning } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { DeepViewShell, DetailCard, FactList, StatusPill } from "../../components/DeepViewShell";
import { FarmSelect } from "../../components/FarmSelect";
import { StatePanel } from "../../components/StatePanel";
import type { FarmRole, StaffMember } from "../../types";
import { useCompanyData } from "./useCompanyData";

export function StaffMemberView() {
  const { memberId = "" } = useParams();
  const request = useMemo(() => ({ kind: "companyStaffMember", memberId } as const), [memberId]);
  const { model, data, notice, pending, act, context } = useCompanyData<StaffMember>(request);
  const navigate = useNavigate();
  const [action, setAction] = useState<"suspend" | "reinstate" | "remove" | "change_role">();
  const [role, setRole] = useState<FarmRole>("worker");
  if (!model || model.state === "loading") return <StatePanel state="loading" />;
  if (model.state !== "ready" || !data) return <StatePanel state={model.state === "ready" ? "empty" : model.state} title="Staff member unavailable" body="This member identifier is missing or outside your authority." actionLabel="Back to Staff" onAction={() => navigate("/company/staff")} />;
  const submit = async () => { const result = await act({ type: "staff.transition", memberId: data.id, action: action!, role: action === "change_role" ? role : undefined }); setAction(undefined); if (result.ok && action === "remove") navigate("/company/staff"); };
  return <DeepViewShell eyebrow="Employment record" title={data.name} subtitle={`${data.role} · Joined ${data.joinedAt}`} breadcrumb={["Company", "Staff", data.name]} backLabel="Back to Staff" onBack={() => navigate("/company/staff")} status={<StatusPill tone={data.status === "active" ? "success" : "warning"}>{data.status.replace("_", " ")}</StatusPill>} actionBar={<><div className="domain-action-summary"><span>{data.activeAssignment ?? "No active Assignment"}</span><p>{data.unresolvedIssues.length ? `${data.unresolvedIssues.length} unresolved issue` : "Custody record clear"}</p></div><div className="domain-action-group">{data.availableActions.includes(data.status === "suspended" ? "reinstate" : "suspend") ? <button type="button" className="domain-secondary-action" onClick={() => setAction(data.status === "suspended" ? "reinstate" : "suspend")}>{data.status === "suspended" ? "Reinstate" : "Suspend"}</button> : null}{data.availableActions.includes("change_role") ? <button type="button" className="domain-secondary-action" onClick={() => { setRole(data.role); setAction("change_role"); }}>Change Role</button> : null}{data.availableActions.includes("remove") ? <button type="button" className="domain-secondary-action danger" onClick={() => setAction("remove")}>Remove Staff</button> : null}</div></>}>
    {notice ? <div className="domain-notice domain-notice--inline">{notice}</div> : null}
    <div className="domain-two-column"><div className="domain-card-stack"><DetailCard eyebrow="Current responsibility" title={data.activeAssignment ?? "No active Assignment"}><p className="domain-emphasis"><IdentificationBadge size={24} />{data.role} · {data.status.replace("_", " ")}</p><FactList facts={[{ label: "Last activity", value: data.lastActivity }, { label: "Company Cargo", value: `${data.companyCargo} units` }, { label: "Issued materials", value: data.issuedMaterials }, { label: "Permission exceptions", value: data.permissionExceptions.length }]} /></DetailCard><DetailCard eyebrow="Custody" title="Assets and product"><ul className="domain-check-list"><li><Package size={18} />{data.companyCargo ? `${data.companyCargo} Company Cargo units in custody` : "No Company Cargo in custody"}</li><li><Toolbox size={18} />{data.issuedMaterials ? `${data.issuedMaterials} issued materials` : "No issued materials"}</li></ul></DetailCard></div><div className="domain-card-stack"><DetailCard eyebrow="Permission exceptions" title={data.permissionExceptions.length ? "Explicit limits" : "Role defaults"}>{data.permissionExceptions.length ? <ul className="domain-check-list warning">{data.permissionExceptions.map((item) => <li key={item}><ShieldWarning size={18} />{item}</li>)}</ul> : <p className="domain-muted">This member inherits the complete {data.role} role template.</p>}</DetailCard><DetailCard eyebrow="Unresolved issues" title={data.unresolvedIssues.length ? "Action required" : "Clear"}>{data.unresolvedIssues.length ? <ul className="domain-check-list warning">{data.unresolvedIssues.map((item) => <li key={item}><Warning size={18} />{item}</li>)}</ul> : <p className="domain-muted">No operational blockers prevent employment changes.</p>}</DetailCard></div></div>
    {action ? <ConfirmDialog eyebrow="Employment control" title={action === "remove" ? "Remove this Staff member?" : action === "change_role" ? "Change this member's role?" : `${action === "suspend" ? "Suspend" : "Reinstate"} this member?`} confirmLabel={action === "remove" ? "Remove Staff" : action === "change_role" ? "Change Role" : action === "suspend" ? "Suspend Member" : "Reinstate Member"} tone={action === "remove" ? "danger-confirm" : "confirm"} pending={pending} onClose={() => setAction(undefined)} onConfirm={() => void submit()}>{action === "change_role" ? <FarmSelect label="New Role" value={role} options={(context.role === "owner" ? ["worker", "procurement", "supervisor", "manager"] : ["worker", "procurement"]).map((item) => ({ value: item, label: item, description: item === data.role ? "Current role" : "New authority template" }))} onChange={(value) => setRole(value as FarmRole)} /> : null}<p>Active Work, cargo and issued materials will be revalidated before the change is accepted.</p></ConfirmDialog> : null}
  </DeepViewShell>;
}
