import { Archive, ArrowSquareOut, CheckCircle, Package, ShoppingCartSimple, Warning, Warehouse } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { DeepViewShell, DetailCard, FactList, StatusPill } from "../../components/DeepViewShell";
import { FarmSelect } from "../../components/FarmSelect";
import { StatePanel } from "../../components/StatePanel";
import type { WarehouseData, WarehouseItem } from "../../types";
import { useCompanyData } from "./useCompanyData";

type WarehouseTab = "stock" | "reservations" | "incoming" | "discrepancies";

export function WarehouseView() {
  const request = useMemo(() => ({ kind: "companyWarehouse" } as const), []);
  const { model, data, notice, pending, act } = useCompanyData<WarehouseData>(request);
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const tab = (params.get("tab") as WarehouseTab) || "stock";
  const [selectedId, setSelectedId] = useState(params.get("item") ?? "wh-tomato");
  const [quantity, setQuantity] = useState(1);
  const [quality, setQuality] = useState("Fine");
  if (!model || model.state === "loading") return <StatePanel state="loading" />;
  if (model.state !== "ready" || !data) return <StatePanel state={model.state === "ready" ? "empty" : model.state} />;
  const selected = data.items.find((item) => item.id === selectedId) ?? data.items[0];
  const choose = (item: WarehouseItem) => { setSelectedId(item.id); setQuantity(1); setQuality(item.quality[0]?.label ?? "Standard"); setParams({ tab, item: item.id }); };
  const createWholesale = async () => { const result = await act({ type: "warehouse.createWholesale", itemId: selected.id, quantity, quality }); if (result.ok && result.entityId) navigate(`/company/warehouse/wholesale/${result.entityId}/review`, { state: { returnTo: `/company/warehouse?tab=stock&item=${selected.id}` } }); };
  const tabs: WarehouseTab[] = ["stock", "reservations", "incoming", "discrepancies"];
  return <DeepViewShell eyebrow="Company inventory authority" title="Warehouse" subtitle={`${data.capacity.used} of ${data.capacity.total} storage units used · reserved stock remains protected`} breadcrumb={["Company", "Warehouse"]} backLabel="Back to Company" onBack={() => navigate("/company")} status={<StatusPill tone={data.atWarehouse ? "success" : "neutral"}>{data.atWarehouse ? "At Warehouse" : "Remote View"}</StatusPill>} actionBar={<><div className="domain-action-summary"><span>{selected?.name ?? "Warehouse"}</span><p>{selected ? `${selected.available} available · ${selected.reserved} reserved` : "No stock selected"}</p></div><div className="domain-action-group"><button type="button" className="domain-secondary-action" onClick={() => void act({ type: "company.setRoute", destination: "warehouse" })}>Set Route</button>{selected && data.canSellWholesale && selected.category === "produce" && selected.available > 0 ? <button type="button" className="domain-primary-action" disabled={pending} onClick={() => void createWholesale()}><ShoppingCartSimple size={18} />Review Wholesale Sale</button> : null}</div></>}>
    {notice ? <div className="domain-notice domain-notice--inline">{notice}</div> : null}
    <div className="company-tabbar" role="tablist" aria-label="Warehouse records">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? "is-selected" : ""} key={item} onClick={() => setParams({ tab: item, ...(selected ? { item: selected.id } : {}) })}>{item === "stock" ? "Stock" : item === "reservations" ? "Reservations" : item === "incoming" ? "Incoming" : "Discrepancies"}<em>{item === "stock" ? data.items.length : item === "reservations" ? data.reservations.filter((entry) => entry.status !== "released").length : item === "incoming" ? data.incomingCargo.length : data.items.filter((entry) => entry.discrepancy).length}</em></button>)}</div>
    {tab === "stock" ? <div className="domain-two-column warehouse-layout"><DetailCard eyebrow="Inventory" title="Stock by custody unit"><div className="warehouse-stock-list">{data.items.map((item) => <button type="button" className={selected?.id === item.id ? "is-selected" : ""} key={item.id} onClick={() => choose(item)}><Package size={22} /><span><strong>{item.name}</strong><small>{item.location} · {item.category}</small></span><b>{item.total} {item.unit}</b><em data-status={item.status}>{item.status}</em></button>)}</div></DetailCard>{selected ? <div className="domain-card-stack"><DetailCard eyebrow="Selected stock" title={selected.name}><FactList facts={[{ label: "Total", value: `${selected.total} ${selected.unit}` }, { label: "Available", value: selected.available }, { label: "Reserved", value: selected.reserved }, { label: "Incoming", value: selected.incoming }, { label: "Location", value: selected.location }]} /><div className="warehouse-quality">{selected.quality.map((entry) => <span key={entry.label}><strong>{entry.quantity}</strong><small>{entry.label}</small></span>)}</div></DetailCard>{data.canSellWholesale && selected.category === "produce" && selected.available ? <DetailCard eyebrow="Surplus channel" title="Wholesale draft"><FarmSelect label="Quality" value={quality} options={selected.quality.filter((entry) => entry.quantity > 0).map((entry) => ({ value: entry.label, label: entry.label, description: `${entry.quantity} recorded` }))} onChange={setQuality} /><label className="company-number-field"><span>Quantity</span><input type="number" min="1" max={selected.available} value={quantity} onChange={(event) => setQuantity(Math.max(1, Math.min(selected.available, Number(event.target.value) || 1)))} /><small>Only unreserved stock · {selected.available} available</small></label></DetailCard> : null}</div> : null}</div> : null}
    {tab === "reservations" ? <div className="company-record-list">{data.reservations.map((reservation) => <article key={reservation.id}><Archive size={24} /><span><strong>{reservation.sourceLabel}</strong><small>{reservation.id.toUpperCase()} · {reservation.quantity} reserved</small></span><em>{reservation.status}</em><button type="button" onClick={() => navigate(reservation.sourceKind === "buyer_order" ? `/work/orders/${reservation.sourceId}` : reservation.sourceKind === "assignment" ? `/work/assignments/${reservation.sourceId}` : `/work/contracts/active/${reservation.sourceId}`)}>Open Work<ArrowSquareOut size={15} /></button>{reservation.status === "active" && data.canManage ? <button type="button" className="is-primary" disabled={pending} onClick={() => void act({ type: "warehouse.prepareOrder", reservationId: reservation.id })}>{data.atWarehouse ? "Prepare" : "Warehouse required"}</button> : null}</article>)}</div> : null}
    {tab === "incoming" ? <div className="company-record-list">{data.incomingCargo.map((cargo) => <article key={cargo.id}><Warehouse size={24} /><span><strong>{cargo.product}</strong><small>{cargo.reference} · {cargo.custodian}</small></span><em>{cargo.status.replace("_", " ")}</em><b>{cargo.quantity} {cargo.unit}</b><button type="button" onClick={() => navigate("/company/cargo")}>View Cargo<ArrowSquareOut size={15} /></button></article>)}</div> : null}
    {tab === "discrepancies" ? <div className="company-record-list">{data.items.filter((item) => item.discrepancy).map((item) => <article className="is-warning" key={item.id}><Warning size={24} /><span><strong>{item.name}</strong><small>{item.discrepancy}</small></span><em>Review</em><button type="button" onClick={() => { choose(item); setParams({ tab: "stock", item: item.id }); }}>Inspect Stock<ArrowSquareOut size={15} /></button></article>)}{!data.items.some((item) => item.discrepancy) ? <div className="inline-empty"><CheckCircle size={22} />No Warehouse discrepancies are open.</div> : null}</div> : null}
  </DeepViewShell>;
}
